Request presentation
scoir/canis pull request #77
Opened 2020-10-08 02:52 UTC by m00sey

Before I go crazy testing everything wanted a review on this implementation.

I tried to isolate `request_presentations~attach` as that differs between indy/dif/jsonlds

2020-10-08 03:10 UTC, m00sey commented on pkg/static/canis-apiserver_swagger.go
> +		mime:  "",
so didn't mean to do this?

2020-10-08 03:23 UTC, m00sey commented
> Enhance data model and datastore APIs for persisting needed data out of proof presentation.

blek this is missing

2020-10-08 12:59 UTC, pfeairheller approved these changes

2020-10-08 12:59 UTC, pfeairheller commented on docker/canis/Dockerfile
> +#RUN apt-get install -y ca-certificates
we should get rid of the commented lines.

2020-10-08 12:59 UTC, pfeairheller commented on pkg/apiserver/admin-presentproof.go
> +	panic("implement me")
Isn't this the last piece to tying it all together?

2020-10-08 12:59 UTC, pfeairheller commented on pkg/presentproof/engine/jsonld/engine.go
> +	return "??"
LDS/LD-Proof?

2020-10-14 19:47 UTC, pfeairheller requested changes
Sweet stuff, only 2 changes needed.

2020-10-14 19:47 UTC, pfeairheller commented on deploy/canis-chart/templates/apiserver-configmap.yaml
> +      grpc:
This needs to say "verifier"

2020-10-14 19:47 UTC, pfeairheller commented on pkg/presentproof/engine/indy/engine.go
> +	return b, nil
We either need to base64 encode the return here... (see below)

2020-10-14 19:47 UTC, pfeairheller commented on pkg/presentproof/engine/registry.go
> +				},
Or base64 encode what we get here...

2020-10-14 20:09 UTC, pfeairheller approved these changes

2020-10-14 21:27 UTC, merged